aws:
  region: us-east-1
server:
  port: 55500

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.pelokqjwdnsjxoveqqhk
    password: woonga
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: TRACE
    org.hibernate.resource.transaction: TRACE
